function getLipidomicsPheno
% define/fetch lipidomic (NMR) phenotypes

pheno = readtable("NMR_Metabolomics_meta.xlsx", ...
    TextType="string", ...
    VariableNamingRule="preserve");

% prepare data-fields to be fetched
pheno.datafield_ukb = string(pheno.datafield_ukb);

% first call to fetch the data from RAP
phenoParser(query=repmat("", height(pheno), 1),...
    df=pheno.datafield_ukb, ...
    tag=pheno.name_ukb, ...
    all=true,...
    instance="0", ...
    ukbrap=true,...
    surv=false);

% run REGENIE step 1 to fit models
traits = matlab.lang.makeValidName(pheno.name_ukb);
covars = ["Age", "Sex", "BMI"];

out_path = fullfile(pwd, "step1");
if ~isfolder(out_path), mkdir(out_path); end

for k = 1:numel(traits)

    out_dir = fullfile(out_path, traits(k));
    if ~isfolder(out_dir), mkdir(out_dir); end

    call_regenie(step=1, ...
        bed="/dnax/GRM/ukb.qcn.indep.chr1-22.bed", ...
        trait=traits(k), ...
        covar=covars, ...
        agesexInt=true, ...
        threads=30, ...
        bsize=1000,...
        out=fullfile(out_dir, traits(k)))
end

end % END